spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  security:
    oauth2:
      esourceserver:
        jwt:
          issuer-uri: http://localhost:9999/auth/realms/one

